name: beatmods-upload
description: Automatically upload artifacts to beatmods
author: Aeroluna

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: upload-cloud
  color: gray-dark

# Define your inputs here.
inputs:
  mods:
    description: Mod ids mapped to Beatmods ids
    required: true
    default: '{}'

# Define your outputs here.
#outputs:
#  time:
#    description: Your output description here

runs:
  using: node20
  main: dist/index.js
