name: beatmods-upload
description: Automatically upload artifacts to beatmods
author: Aeroluna

branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  path:
    description: Path to get zips from
    required: false
    default: './artifacts'
  mods:
    description: Mod ids mapped to Beatmods ids
    required: true
    default: '{}'
  token:
    description: A Github PAT
    required: true
    default: ''

runs:
  using: node20
  main: dist/index.js
